version: "3.8"

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./webapp:/var/www/html
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - net1
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: Laravel
      TZ: "Asia/Tokyo"
    networks:
      - net1
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d 
networks:
  net1: